### ISSUE TITLE
Scheme Details: "Last Day to Pay: " Add string "___ of every month" instead of only mentioning a date (see screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/ajoor-project#140]
![Scheme details - Last day to pay](https://user-images.githubusercontent.com/53593496/64410965-976a0600-d0a5-11e9-9d7a-aa6857d858b2.JPG)

**Comment by danialshakeel** [comment]
@isabeen can you clarify this one.

**Comment by maryam-awan** [comment]
add txt "every month"

**Comment by isabeen** [comment]
@danialshakeel Last day of payment should be written as: '5th **of every month**' instead of only 5th ...
According to the apps.

**Comment by danialshakeel** [comment]
I have been followin the android app and son't think there is a text as "of every month" in it

**Comment by isabeen** [comment]
@danialshakeel here you go.
![WhatsApp Image 2019-09-17 at 10 55 21 AM](https://user-images.githubusercontent.com/53593496/65015047-dd428c00-d939-11e9-8079-c73f9fff816c.jpeg)

**Comment by danialshakeel** [comment]
Check Your teams @isabeen

**Comment by isabeen** [comment]
This only applies for Monthly schemes @danialshakeel

**Comment by danialshakeel** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/40662656/65015246-6659c300-d93a-11e9-9152-46e3dcad8fcd.png)
as I already told You,, I followed the android App.

**Comment by isabeen** [comment]
As it is only done in iOS, this issues won't be worked on.
