### ISSUE TITLE
Balance -> Withdraw: Calculation error (total payment should subtract 100 from total amount.

### ISSUE THREAD

**Issue by isabeen** [sofittech/ajoor-project#195]
![web](https://user-images.githubusercontent.com/53593496/66377282-b7555800-e9ca-11e9-87c3-6ec54223ecb8.jpg)

**Comment by danialshakeel** [comment]
![WhatsApp Image 2019-10-08 at 12 58 49 PM](https://user-images.githubusercontent.com/40662656/66377889-e0c2b380-e9cb-11e9-99a1-f19dd0103b21.jpeg)

**Comment by isabeen** [comment]
@danialshakeel I've ask them to change it.
