### ISSUE TITLE
My Schemes: Showing Status of old schemes as running

### ISSUE THREAD

**Issue by isabeen** [sofittech/ajoor-project#197]
Account: khannssabeen@gmail.com (123)

Screen: **My Schemes**

This screen is showing the status of ads in preview (unlike iOS and web)
**Issue:** The status of expired (old schemes) is also shown as running.

Old Schemes: 27th Sept Web
19th Sept

![catsbbb](https://user-images.githubusercontent.com/53593496/66387841-3bfda180-e9de-11e9-80ff-d281e680d43a.jpg)

**Comment by mohsinabid** [comment]
Done
