### ISSUE TITLE
Scheme Details -> Participants -> Add More: All participants who have accepted the scheme should appear under participants bar (Only for Pending Schemes)

### ISSUE THREAD

**Issue by isabeen** [sofittech/ajoor-project#205]
If a scheme is not started yet, but participants have accepted it, they all should appear on the Add More Screen

![nnnnnn](https://user-images.githubusercontent.com/53593496/66461299-277ae100-ea92-11e9-87c6-c19ffe85c305.jpg)
![bbbb](https://user-images.githubusercontent.com/53593496/66461303-2ba6fe80-ea92-11e9-9015-c021f47048dd.JPG)

**Comment by HaseemUlHaq** [comment]
@danialshakeel test
