### ISSUE TITLE
Weekly Scheme - Participants Screen Error. (see details)

### ISSUE THREAD

**Issue by isabeen** [sofittech/ajoor-project#206]
**Issue:** Empty Participants Screen (see screenshots)
Pay now of this scheme is also not responsive due to the issue

**Scheme name:** DIAMOND

**Participants:** (4)
sabeenjavaid@sofit.ltd (123) ---- **Scheme Owner**
khannssabeen@gmail.com (123) 
shakhsdevelopers@gmail.com (123) 
maryama@gmail.com (123) 

**Scheme type**: Weekly

**Start date:** 9th Oct, 2019
**Amount:** 4000 USD

Scheme details:
![WhatsApp Image 2019-10-09 at 12 59 43 PM](https://user-images.githubusercontent.com/53593496/66462588-dddfc580-ea94-11e9-98ca-d086178e3db1.jpeg)

Participants Screen:
![nnn](https://user-images.githubusercontent.com/53593496/66462669-010a7500-ea95-11e9-8ab1-cbea2c53f0b3.jpg)

**Comment by sheerazanwar** [comment]
While testing this issue by postman on ajoor-dev.herokuapp.com, response contains all participants as it was earlier.
For clarification Usman and Mohsin have to check the logs either response is same as given below or not.
`{
    "success": true,
    "assigned": [
        {
            "_id": "5d9d914964e0790033427e40",
            "ajoor_id": {
                "_id": "5d9d770764e0790033427dd7",
                "name": "DIAMOND",
                "createdBy": {
                    "_id": "5d943dc9fb3b000033f4ba3f",
                    "email": "sabeenjavaid@sofit.ltd",
                    "address": "Bahria",
                    "state": "Luxury Heights",
                    "username": "",
                    "city": "Ras al Khaimah",
                    "country": "United Arab Emirates",
                    "mobile": "+923315608968 ",
                    "name": "Sabeen Sofit ",
                    "__v": 0,
                    "stripeID": "cus_FuqdBYH47HUT6Y",
                    "defaultCard": "card_1FP1b2F1OBmYBo1EjN2UREUK",
                    "autoPayment": false,
                    "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569996407/sntlypj6wqfsdrrancm6.jpg",
                    "fcmToken": "fcXT3wuDs6Q:APA91bHLs-wNV-CVwynLcxYwPVakBEY448SFcri3xrWXOheRBTCEpAthgHh2OUS_L8TYAo8jteLBDu-_B6GHV4_9UdjcrOOPhOLpFcCdxko6Y2P4MKPfcudvAt_lycywyXSHrQ1pdNdl",
                    "isDeleted": false,
                    "reason": "",
                    "isAdmin": false,
                    "connections": [],
                    "emailVerfication": false,
                    "smsVerification": true,
                    "isBlocked": false,
                    "currency": "AED"
                },
                "planType": "5c6556996e28165535280f3a",
                "installment": 250,
                "__v": 8,
                "type": "",
                "scheduled": true,
                "expectedUsers": 4,
                "notificationDay": null,
                "payment_id": [],
                "invitedUsers": [
                    "5ca73612869c740034afc13b",
                    "5d9b00f9b931c50033f37b03"
                ],
                "participants": [
                    "5d943dc9fb3b000033f4ba3f",
                    "5d677e088c86390033619000",
                    "5d6771588c86390033618ff0",
                    "5d63abf7bd8bfb003300606a"
                ],
                "createdAt": "2019-10-09T04:57:34.177Z",
                "description": "Weekly scheme testing with 4 participants ",
                "currency": "USD",
                "amount": 4000,
                "endDate": "2020-01-29T05:57:31.000Z",
                "startDate": "2019-10-09T05:57:31.000Z"
            },
            "user_id": {
                "_id": "5d943dc9fb3b000033f4ba3f",
                "email": "sabeenjavaid@sofit.ltd",
                "address": "Bahria",
                "state": "Luxury Heights",
                "username": "",
                "city": "Ras al Khaimah",
                "country": "United Arab Emirates",
                "mobile": "+923315608968 ",
                "name": "Sabeen Sofit ",
                "__v": 0,
                "stripeID": "cus_FuqdBYH47HUT6Y",
                "defaultCard": "card_1FP1b2F1OBmYBo1EjN2UREUK",
                "autoPayment": false,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569996407/sntlypj6wqfsdrrancm6.jpg",
                "fcmToken": "fcXT3wuDs6Q:APA91bHLs-wNV-CVwynLcxYwPVakBEY448SFcri3xrWXOheRBTCEpAthgHh2OUS_L8TYAo8jteLBDu-_B6GHV4_9UdjcrOOPhOLpFcCdxko6Y2P4MKPfcudvAt_lycywyXSHrQ1pdNdl",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "AED"
            },
            "__v": 0,
            "payment_id": [],
            "type": "withdraw",
            "assignmentDate": "2019-11-06T05:57:31.000Z",
            "amount": 0,
            "currency": "USD",
            "status": "pending"
        },
        {
            "_id": "5d9d914964e0790033427e41",
            "ajoor_id": {
                "_id": "5d9d770764e0790033427dd7",
                "name": "DIAMOND",
                "createdBy": {
                    "_id": "5d943dc9fb3b000033f4ba3f",
                    "email": "sabeenjavaid@sofit.ltd",
                    "address": "Bahria",
                    "state": "Luxury Heights",
                    "username": "",
                    "city": "Ras al Khaimah",
                    "country": "United Arab Emirates",
                    "mobile": "+923315608968 ",
                    "name": "Sabeen Sofit ",
                    "__v": 0,
                    "stripeID": "cus_FuqdBYH47HUT6Y",
                    "defaultCard": "card_1FP1b2F1OBmYBo1EjN2UREUK",
                    "autoPayment": false,
                    "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569996407/sntlypj6wqfsdrrancm6.jpg",
                    "fcmToken": "fcXT3wuDs6Q:APA91bHLs-wNV-CVwynLcxYwPVakBEY448SFcri3xrWXOheRBTCEpAthgHh2OUS_L8TYAo8jteLBDu-_B6GHV4_9UdjcrOOPhOLpFcCdxko6Y2P4MKPfcudvAt_lycywyXSHrQ1pdNdl",
                    "isDeleted": false,
                    "reason": "",
                    "isAdmin": false,
                    "connections": [],
                    "emailVerfication": false,
                    "smsVerification": true,
                    "isBlocked": false,
                    "currency": "AED"
                },
                "planType": "5c6556996e28165535280f3a",
                "installment": 250,
                "__v": 8,
                "type": "",
                "scheduled": true,
                "expectedUsers": 4,
                "notificationDay": null,
                "payment_id": [],
                "invitedUsers": [
                    "5ca73612869c740034afc13b",
                    "5d9b00f9b931c50033f37b03"
                ],
                "participants": [
                    "5d943dc9fb3b000033f4ba3f",
                    "5d677e088c86390033619000",
                    "5d6771588c86390033618ff0",
                    "5d63abf7bd8bfb003300606a"
                ],
                "createdAt": "2019-10-09T04:57:34.177Z",
                "description": "Weekly scheme testing with 4 participants ",
                "currency": "USD",
                "amount": 4000,
                "endDate": "2020-01-29T05:57:31.000Z",
                "startDate": "2019-10-09T05:57:31.000Z"
            },
            "user_id": {
                "_id": "5d677e088c86390033619000",
                "name": "Khan",
                "city": "xyz",
                "state": "xyz",
                "email": "khannssabeen@gmail.com",
                "address": "xyz",
                "username": "",
                "mobile": "+923315608968",
                "country": "Pakistan",
                "__v": 0,
                "stripeID": "cus_Fi8HLRYB3EAMqM",
                "defaultCard": "card_1FEAEMF1OBmYBo1ELx3PSDXd",
                "autoPayment": true,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569579542/z9nazpocmmmchqxqeai8.jpg",
                "fcmToken": "ffnKvN3Jz-c:APA91bGhsWitM9RIgfadTgC2WFD7KbjVWb-RnQgOy7kLqQeCgDp9hIJeTEYpGHeF0aa4QTrlGgyXJRf4mWXyUorOULEE1jXZ-yYEWZYYmqrUQb0NMS75EmKQ0coyhlwhsYFmxrar21Ss",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "AED"
            },
            "__v": 0,
            "payment_id": [],
            "type": "withdraw",
            "assignmentDate": "2019-12-04T05:57:31.000Z",
            "amount": 0,
            "currency": "USD",
            "status": "pending"
        },
        {
            "_id": "5d9d914964e0790033427e42",
            "ajoor_id": {
                "_id": "5d9d770764e0790033427dd7",
                "name": "DIAMOND",
                "createdBy": {
                    "_id": "5d943dc9fb3b000033f4ba3f",
                    "email": "sabeenjavaid@sofit.ltd",
                    "address": "Bahria",
                    "state": "Luxury Heights",
                    "username": "",
                    "city": "Ras al Khaimah",
                    "country": "United Arab Emirates",
                    "mobile": "+923315608968 ",
                    "name": "Sabeen Sofit ",
                    "__v": 0,
                    "stripeID": "cus_FuqdBYH47HUT6Y",
                    "defaultCard": "card_1FP1b2F1OBmYBo1EjN2UREUK",
                    "autoPayment": false,
                    "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569996407/sntlypj6wqfsdrrancm6.jpg",
                    "fcmToken": "fcXT3wuDs6Q:APA91bHLs-wNV-CVwynLcxYwPVakBEY448SFcri3xrWXOheRBTCEpAthgHh2OUS_L8TYAo8jteLBDu-_B6GHV4_9UdjcrOOPhOLpFcCdxko6Y2P4MKPfcudvAt_lycywyXSHrQ1pdNdl",
                    "isDeleted": false,
                    "reason": "",
                    "isAdmin": false,
                    "connections": [],
                    "emailVerfication": false,
                    "smsVerification": true,
                    "isBlocked": false,
                    "currency": "AED"
                },
                "planType": "5c6556996e28165535280f3a",
                "installment": 250,
                "__v": 8,
                "type": "",
                "scheduled": true,
                "expectedUsers": 4,
                "notificationDay": null,
                "payment_id": [],
                "invitedUsers": [
                    "5ca73612869c740034afc13b",
                    "5d9b00f9b931c50033f37b03"
                ],
                "participants": [
                    "5d943dc9fb3b000033f4ba3f",
                    "5d677e088c86390033619000",
                    "5d6771588c86390033618ff0",
                    "5d63abf7bd8bfb003300606a"
                ],
                "createdAt": "2019-10-09T04:57:34.177Z",
                "description": "Weekly scheme testing with 4 participants ",
                "currency": "USD",
                "amount": 4000,
                "endDate": "2020-01-29T05:57:31.000Z",
                "startDate": "2019-10-09T05:57:31.000Z"
            },
            "user_id": {
                "_id": "5d6771588c86390033618ff0",
                "country": "United Arab Emirates",
                "address": "UAE",
                "city": "Abu Dhabi",
                "name": "SHAKHS",
                "mobile": "+923315608968",
                "state": "UAE",
                "email": "shakhsdevelopers@gmail.com",
                "__v": 0,
                "stripeID": "cus_Fi7PyQcaKNsvXW",
                "defaultCard": "card_1FChHeF1OBmYBo1Eu3eqxm7a",
                "autoPayment": false,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1568889750/masgdytdzkzs62qo7sa7.jpg",
                "fcmToken": "cQSOYalz50A:APA91bFJGDYesIbo49wqwtGwzfSkjvSKqkVaAxI6PjD-zli3dYdUwmoHLrm8k-ilmCNRPsvs82e2jUzV6UtnFmxe9-Y8EoQm5uv6gxo-TZqAFEEfsnQZ2p2O-Q4pPs3443jAMO4lnxQQ",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "PKR"
            },
            "__v": 0,
            "payment_id": [],
            "type": "withdraw",
            "assignmentDate": "2020-01-01T05:57:31.000Z",
            "amount": 0,
            "currency": "USD",
            "status": "pending"
        },
        {
            "_id": "5d9d914964e0790033427e43",
            "ajoor_id": {
                "_id": "5d9d770764e0790033427dd7",
                "name": "DIAMOND",
                "createdBy": {
                    "_id": "5d943dc9fb3b000033f4ba3f",
                    "email": "sabeenjavaid@sofit.ltd",
                    "address": "Bahria",
                    "state": "Luxury Heights",
                    "username": "",
                    "city": "Ras al Khaimah",
                    "country": "United Arab Emirates",
                    "mobile": "+923315608968 ",
                    "name": "Sabeen Sofit ",
                    "__v": 0,
                    "stripeID": "cus_FuqdBYH47HUT6Y",
                    "defaultCard": "card_1FP1b2F1OBmYBo1EjN2UREUK",
                    "autoPayment": false,
                    "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569996407/sntlypj6wqfsdrrancm6.jpg",
                    "fcmToken": "fcXT3wuDs6Q:APA91bHLs-wNV-CVwynLcxYwPVakBEY448SFcri3xrWXOheRBTCEpAthgHh2OUS_L8TYAo8jteLBDu-_B6GHV4_9UdjcrOOPhOLpFcCdxko6Y2P4MKPfcudvAt_lycywyXSHrQ1pdNdl",
                    "isDeleted": false,
                    "reason": "",
                    "isAdmin": false,
                    "connections": [],
                    "emailVerfication": false,
                    "smsVerification": true,
                    "isBlocked": false,
                    "currency": "AED"
                },
                "planType": "5c6556996e28165535280f3a",
                "installment": 250,
                "__v": 8,
                "type": "",
                "scheduled": true,
                "expectedUsers": 4,
                "notificationDay": null,
                "payment_id": [],
                "invitedUsers": [
                    "5ca73612869c740034afc13b",
                    "5d9b00f9b931c50033f37b03"
                ],
                "participants": [
                    "5d943dc9fb3b000033f4ba3f",
                    "5d677e088c86390033619000",
                    "5d6771588c86390033618ff0",
                    "5d63abf7bd8bfb003300606a"
                ],
                "createdAt": "2019-10-09T04:57:34.177Z",
                "description": "Weekly scheme testing with 4 participants ",
                "currency": "USD",
                "amount": 4000,
                "endDate": "2020-01-29T05:57:31.000Z",
                "startDate": "2019-10-09T05:57:31.000Z"
            },
            "user_id": {
                "_id": "5d63abf7bd8bfb003300606a",
                "username": "",
                "address": "Islamabad",
                "state": "Pakistan",
                "mobile": "+923349515596",
                "name": "Maryam Awan",
                "country": "Pakistan",
                "email": "maryama@gmail.com",
                "city": "Islamabad",
                "__v": 0,
                "stripeID": "cus_Fh2yyguQqFZWtl",
                "defaultCard": "card_1FBhRbF1OBmYBo1EEaguHRSh",
                "autoPayment": true,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1566991943/gjf9llxzgwwhjd1kzenp.jpg",
                "fcmToken": "dThZM6W8BfE:APA91bH7M0NoShviSv_IxtPzHzgWXN4lwQGd3KBIy5Nn8lUK9xY9vEWpY7WHICJQd1brCca1d6D-41S18v5-utvtg51OohU0QdIuHIAmtwdVMuwv8QrfOyW9eZKYH2jKbvgFBkHJBPUR",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "PKR"
            },
            "__v": 0,
            "payment_id": [],
            "type": "withdraw",
            "assignmentDate": "2020-01-29T05:57:31.000Z",
            "amount": 0,
            "currency": "USD",
            "status": "pending"
        }
    ],
    "result": {
        "_id": "5d9d770764e0790033427dd7",
        "name": "DIAMOND",
        "createdBy": {
            "_id": "5d943dc9fb3b000033f4ba3f",
            "email": "sabeenjavaid@sofit.ltd",
            "address": "Bahria",
            "state": "Luxury Heights",
            "username": "",
            "city": "Ras al Khaimah",
            "country": "United Arab Emirates",
            "mobile": "+923315608968 ",
            "name": "Sabeen Sofit ",
            "__v": 0,
            "stripeID": "cus_FuqdBYH47HUT6Y",
            "defaultCard": "card_1FP1b2F1OBmYBo1EjN2UREUK",
            "autoPayment": false,
            "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569996407/sntlypj6wqfsdrrancm6.jpg",
            "fcmToken": "fcXT3wuDs6Q:APA91bHLs-wNV-CVwynLcxYwPVakBEY448SFcri3xrWXOheRBTCEpAthgHh2OUS_L8TYAo8jteLBDu-_B6GHV4_9UdjcrOOPhOLpFcCdxko6Y2P4MKPfcudvAt_lycywyXSHrQ1pdNdl",
            "isDeleted": false,
            "reason": "",
            "isAdmin": false,
            "connections": [],
            "emailVerfication": false,
            "smsVerification": true,
            "isBlocked": false,
            "currency": "AED"
        },
        "planType": {
            "_id": "5c6556996e28165535280f3a",
            "name": "Weekly",
            "type": "weekly"
        },
        "installment": 250,
        "__v": 8,
        "type": "selfCreated",
        "scheduled": true,
        "expectedUsers": 4,
        "notificationDay": null,
        "payment_id": [],
        "invitedUsers": [
            {
                "_id": "5ca73612869c740034afc13b",
                "country": "Pakistan",
                "address": "pwd",
                "city": "isl",
                "name": "mohsin",
                "mobile": "+923335263109",
                "state": "isl",
                "email": "mohsinabid901@gmail.com",
                "__v": 0,
                "stripeID": "cus_EpUp2X0RZmXZ4W",
                "defaultCard": "card_1ELpu9F1OBmYBo1ETyvT69M8",
                "autoPayment": true,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1567755499/hzd2s11h2oggxm9zokkg.jpg",
                "fcmToken": "e9RPQFjOA2E:APA91bEple4nf2XeXHhM7ORujcjz22Z4-UCogn4LvPgS_nyt6Qf3qugF_zuJcQ0Nz7uC87noBypbXPEu74EDfErw_d8XZ5OSpKQqb7j5TAlXC7T36xlBdy0GFEJE2mwdivhQAFQeDpL5",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "PKR"
            },
            {
                "_id": "5d9b00f9b931c50033f37b03",
                "mobile": "+923315608968",
                "address": "India ",
                "country": "Pakistan",
                "state": "Tunesia",
                "city": "Andrlo",
                "username": "",
                "email": "danialshakeel@sofit.ltd",
                "name": "Dan",
                "__v": 0,
                "stripeID": "cus_FwllK0L4gSlLmt",
                "autoPayment": false,
                "profilePicUrl": "https://res.cloudinary.com/hizi3ayop/image/upload/v1536871210/default.png",
                "fcmToken": "etEcNLf7W5I:APA91bFJqUcfTKa68p6ZlvXft2sgPudJpQ7K6IE88Gf7Q2x8KZwypGu-riV3pfuzi6t51m0rdOZA89mgpVsc7SY8VAcBUkG0cVYmC8cbxDzS8cdaoBV9aQ-wRVYdScCLgoUvYN2wvDGr",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "JPY"
            }
        ],
        "participants": [
            {
                "_id": "5d943dc9fb3b000033f4ba3f",
                "email": "sabeenjavaid@sofit.ltd",
                "address": "Bahria",
                "state": "Luxury Heights",
                "username": "",
                "city": "Ras al Khaimah",
                "country": "United Arab Emirates",
                "mobile": "+923315608968 ",
                "name": "Sabeen Sofit ",
                "__v": 0,
                "stripeID": "cus_FuqdBYH47HUT6Y",
                "defaultCard": "card_1FP1b2F1OBmYBo1EjN2UREUK",
                "autoPayment": false,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569996407/sntlypj6wqfsdrrancm6.jpg",
                "fcmToken": "fcXT3wuDs6Q:APA91bHLs-wNV-CVwynLcxYwPVakBEY448SFcri3xrWXOheRBTCEpAthgHh2OUS_L8TYAo8jteLBDu-_B6GHV4_9UdjcrOOPhOLpFcCdxko6Y2P4MKPfcudvAt_lycywyXSHrQ1pdNdl",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "AED"
            },
            {
                "_id": "5d677e088c86390033619000",
                "name": "Khan",
                "city": "xyz",
                "state": "xyz",
                "email": "khannssabeen@gmail.com",
                "address": "xyz",
                "username": "",
                "mobile": "+923315608968",
                "country": "Pakistan",
                "__v": 0,
                "stripeID": "cus_Fi8HLRYB3EAMqM",
                "defaultCard": "card_1FEAEMF1OBmYBo1ELx3PSDXd",
                "autoPayment": true,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1569579542/z9nazpocmmmchqxqeai8.jpg",
                "fcmToken": "ffnKvN3Jz-c:APA91bGhsWitM9RIgfadTgC2WFD7KbjVWb-RnQgOy7kLqQeCgDp9hIJeTEYpGHeF0aa4QTrlGgyXJRf4mWXyUorOULEE1jXZ-yYEWZYYmqrUQb0NMS75EmKQ0coyhlwhsYFmxrar21Ss",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "AED"
            },
            {
                "_id": "5d6771588c86390033618ff0",
                "country": "United Arab Emirates",
                "address": "UAE",
                "city": "Abu Dhabi",
                "name": "SHAKHS",
                "mobile": "+923315608968",
                "state": "UAE",
                "email": "shakhsdevelopers@gmail.com",
                "__v": 0,
                "stripeID": "cus_Fi7PyQcaKNsvXW",
                "defaultCard": "card_1FChHeF1OBmYBo1Eu3eqxm7a",
                "autoPayment": false,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1568889750/masgdytdzkzs62qo7sa7.jpg",
                "fcmToken": "cQSOYalz50A:APA91bFJGDYesIbo49wqwtGwzfSkjvSKqkVaAxI6PjD-zli3dYdUwmoHLrm8k-ilmCNRPsvs82e2jUzV6UtnFmxe9-Y8EoQm5uv6gxo-TZqAFEEfsnQZ2p2O-Q4pPs3443jAMO4lnxQQ",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "PKR"
            },
            {
                "_id": "5d63abf7bd8bfb003300606a",
                "username": "",
                "address": "Islamabad",
                "state": "Pakistan",
                "mobile": "+923349515596",
                "name": "Maryam Awan",
                "country": "Pakistan",
                "email": "maryama@gmail.com",
                "city": "Islamabad",
                "__v": 0,
                "stripeID": "cus_Fh2yyguQqFZWtl",
                "defaultCard": "card_1FBhRbF1OBmYBo1EEaguHRSh",
                "autoPayment": true,
                "profilePicUrl": "http://res.cloudinary.com/hbdry1wpq/image/upload/v1566991943/gjf9llxzgwwhjd1kzenp.jpg",
                "fcmToken": "dThZM6W8BfE:APA91bH7M0NoShviSv_IxtPzHzgWXN4lwQGd3KBIy5Nn8lUK9xY9vEWpY7WHICJQd1brCca1d6D-41S18v5-utvtg51OohU0QdIuHIAmtwdVMuwv8QrfOyW9eZKYH2jKbvgFBkHJBPUR",
                "isDeleted": false,
                "reason": "",
                "isAdmin": false,
                "connections": [],
                "emailVerfication": false,
                "smsVerification": true,
                "isBlocked": false,
                "currency": "PKR"
            }
        ],
        "createdAt": "2019-10-09T04:57:34.177Z",
        "description": "Weekly scheme testing with 4 participants ",
        "currency": "USD",
        "amount": 4000,
        "endDate": "2020-01-29T05:57:31.000Z",
        "startDate": "2019-10-09T05:57:31.000Z"
    },
    "currentWeek": 1
}`

**Comment by isabeen** [comment]
@UsmanTahir101 @Farasatullah @danialshakeel  @mohsinabid  please have a look at this issue.

**Comment by mohsinabid** [comment]
OK

**Comment by isabeen** [comment]
@sheerazanwar payment id: [ ] is null

**Comment by isabeen** [comment]
@sheerazanwar for this scheme (DIAMOND), payments for only one month (OCT) is showing and therefore, the payment is received by only person.

However, issue exits for another weekly scheme called XYZ. 
(sabeenjavaid@sofit.ltd)

**Comment by isabeen** [comment]
@sheerazanwar not resolved yet. Made a new scheme named 'Water' from the same account.
